# vim:tw=0:ts=2:sw=2:noet:ft=make
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/doblabs/easy-as-pypi-config#🍐
# License: MIT

EAPP_MAKEFILE_PYDOCSTYLE_DISABLE ?= true

